### ISSUE TITLE
Pairing UI needs work

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#67] opened 2017-02-06 21:53 UTC
Kids are confused about how to connect the kindle to the flutter board. They are not sure if they should press the white button or press and hold the button. What order do they press scan and the button? 

They don't realize they need to click on the name of the board in the app - it doesn't look particularly clickable.

They are confused about why they see multiple names listed, or other people's board names.

**Comment by jenncross** [comment] 2017-02-08 20:37
I think the order of pressing scan and the physical button does not matter - so long as both happen. But that should be tested.

The need to click on the list issue is connected to or a duplicate of issue #24  for making the list of names look more like the interface.

The understanding of why multiple names may be best to correct in training and instruction when discussing how to connect.

**Comment by pdille** [comment] 2017-02-21 21:28
Fixed in 615e9d3f52

**Closed by pdille** 2017-02-21 21:28 UTC
Labels: enhancement, module - connect tab, module - UI
